# Generated by Django 5.1.1 on 2025-05-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('pharmacists', 'Pharmacists'), ('doctor', 'Doctor')], default='pharmacists', max_length=20),
        ),
    ]
