# Generated by Django 5.1.1 on 2025-05-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='uploaded_file',
            field=models.ImageField(upload_to='prescriptions/'),
        ),
    ]
