# Generated by Django 5.1.5 on 2025-05-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_alter_prescription_uploaded_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
