# Generated by Django 5.1.2 on 2025-06-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0011_prescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='sent_to_pharmacist',
            field=models.BooleanField(default=False),
        ),
    ]
